name: PR build

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Read Maven version
        id: maven-version
        run: echo "version=$(cat .github/vars/maven-version.txt)" >> $GITHUB_OUTPUT

      - name: Setup Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: '3.13'

      - name: Run pre-commit
        uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1

  maven-build:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        java: [11, 17, 21, 25]
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install docker-credential-fake
        run: |
          sudo cp docker-credential-fake /usr/bin/docker-credential-fake

      - name: Read Maven version
        id: maven-version
        run: echo "version=$(cat .github/vars/maven-version.txt)" >> $GITHUB_OUTPUT

      - name: Setup Maven Action
        uses: s4u/setup-maven-action@ba34de01b7f4ba2ab8e2860df8993a29f4477056 # v1.20.0
        with:
          checkout-enabled: false
          java-distribution: 'temurin'
          java-version: ${{ matrix.java }}
          maven-version: ${{ steps.maven-version.outputs.version }}
          cache-enabled: true

      - name: Maven build
        run: mvn --batch-mode --update-snapshots verify
