name: Deploy Javadoc

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  deploy-javadoc:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Read Maven version
        id: maven-version
        run: echo "version=$(cat .github/vars/maven-version.txt)" >> $GITHUB_OUTPUT

      - name: Setup Maven Action
        uses: s4u/setup-maven-action@ba34de01b7f4ba2ab8e2860df8993a29f4477056 # v1.20.0
        with:
          checkout-enabled: false
          java-distribution: 'temurin'
          java-version: 11
          maven-version: ${{ steps.maven-version.outputs.version }}
          cache-enabled: true

      - name: Build javadoc
        run: mvn generate-resources javadoc:javadoc

      - name: Upload javadoc
        id: upload-javadoc
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          path: target/reports/apidocs/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
